ECPINT-1143: handle klarna void action
checkout/checkout-shopware6-plugin pull request #6
Opened 2020-12-04 08:49 UTC by ved-beejadhur-cko

**Jira:** [ECPINT-1143](https://checkout.atlassian.net/browse/ECPINT-1143)

### Notes

This Pull Request handles klarna void action on the admin side

### Housekeeping

- [ ] Unit & Integrations tests
- [ ] Updated relevant documentation
- [ ] Manually tested new functionality

2020-12-08 08:09 UTC, mitja-kramberger-cko commented on src/Helper/Url.php
> +        if($param['payment_method'] == "Klarna") {
This is fine, as Middleware is currently just a pass-through.

2020-12-08 08:10 UTC, mitja-kramberger-cko commented on src/Resources/app/administration/src/components/cko-modal/index.js
> +        if (
Remove `console.log`, and refactor status checks (and page reload) to a common hander.

2020-12-08 08:29 UTC, mitja-kramberger-cko commented on src/Resources/app/administration/src/components/cko-modal/index.js
> +      if (paymentMethod === "Sofort" || paymentMethod === "Sepa") {
Can we avoid coding against a specific payment method, maybe something like:

```
      if (this.orderInfo.customFields.payment_pending.payment_id) {
        paymentID = this.orderInfo.customFields.payment_pending.payment_id;
      } else {
        paymentID = this.orderInfo.customFields.payment_approved.payment_id;
     }
```

2020-12-08 08:32 UTC, mitja-kramberger-cko requested changes
@ved-beejadhur-cko PR comments also apply to https://github.com/checkout/checkout-shopware6-plugin/pull/5

2020-12-15 10:18 UTC, ved-beejadhur-cko commented
> @ved-beejadhur-cko PR comments also apply to #5

modification done

2020-12-16 08:32 UTC, mitja-kramberger-cko approved these changes

2020-12-18 04:24 UTC, merged